services:
  app:
    build:
      context: src
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/tronparser
      - TRONPY_TIMEOUT=10.
      - TRONPY_NETWORK=nile

  postgres:
    image: postgres:alpine
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=tronparser
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 3s